### PR TITLE
move t,i querystring parameters to the beginning + fix the address qu…

### LINKED ISSUE #556: Refactor backend request URL generation
- no fixed params as `a` values also might change with handleReadStart
- move `t` and `i` to the beginning

### PR DESCRIPTION
**Pull request by peuter**
…eue feature (only request start page address states first)

closes #556

### CODE REVIEW

File: client/source/class/cv/io/Client.js [hunk 1]
```diff
@@ -408,19 +420,11 @@ qx.Class.define('cv.io.Client', {
...
-              qs += key + "=" + data[key].join("&"+key+"=")+"&";
-            } else {
-              qs += key + "=" + data[key] + "&";
-            }
-          });
-          url = qx.util.Uri.appendParamsToUrl(url, qs.substring(0, qs.length-1));
+          qs = this.getQueryString(data);
+          url = qx.util.Uri.appendParamsToUrl(url, qs);
         }
+        console.log(qs);
```
Comment (ChristianMayer) [inline client/source/class/cv/io/Client.js]: Isn't that a left over that shouldn't be in this PR?

Comment (peuter) [inline client/source/class/cv/io/Client.js]: You are right -> removed
